### ISSUE TITLE
glTexImage3D identifier not found

### ISSUE THREAD

**Issue by Git-me-outta-here** [ojaswa/Blaze#1]
I've tried to compile this with Qt 5.9.9 and Qt 5.15.0. Both of them give me these errors:
Blaze\src\ui\glwidget.cpp(278,5): error C3861: 'glTexImage3D': identifier not found
and
Blaze\src\algorithm\volumemanager.cpp	450	 Error C2131	expression did not evaluate to a constant	

Is there some configuration I'm missing? I've compiled ITK and VTK successfully.

**Comment by ojaswa** [comment]
> I've tried to compile this with Qt 5.9.9 and Qt 5.15.0. Both of them give me these errors:
> Blaze\src\ui\glwidget.cpp(278,5): error C3861: 'glTexImage3D': identifier not found
> and
> Blaze\src\algorithm\volumemanager.cpp 450 Error C2131 expression did not evaluate to a constant
> 
> Is there some configuration I'm missing? I've compiled ITK and VTK successfully.

This has to do with OpenGL installation on your system. Please ensure that you have appropriate graphics driver and OpenGL libs installed.

The other error is a compiler issue on Windows. Change the following:
`int points_allocated[m_materials.size()];` 
to:
`int points_allocated  = new int[m_materials.size()];`
and later deallocate (by the end of function) as:
`delete []points_allocated;`

**Comment by Git-me-outta-here** [comment]
Thank you for your help!

Could you specify which OpenGL libs are required? I assume I have to set a path in CMake somewhere.

**Comment by Git-me-outta-here** [comment]
Also, the line you suggested does not work:
` int points_allocated = new int[m_materials.size()];`
gives this error:
Error (active)	E0144	a value of type "int *" cannot be used to initialize an entity of type "int"	Blaze	Blaze\src\algorithm\volumemanager.cpp	451

**Comment by Git-me-outta-here** [comment]
` int *points_allocated = new int[m_materials.size()];`
should work.
still wondering about the OpenGL libs however

**Comment by ojaswa** [comment]
OpenGL 3.3 or above should work just fine.
